# Generated by Django 5.2.5 on 2025-08-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shorten', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short',
            name='shortCode',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
